Update metaRC_alt-openbsd

diff --git a/metaRC_alt-openbsd b/metaRC_alt-openbsd
--- a/metaRC_alt-openbsd
+++ b/metaRC_alt-openbsd
@@ -107,85 +107,91 @@ netest () {
 }
 
 extract () {
-    if [ -f $1 ] ; then
-        case $1 in
-            *.tar.bz2)   tar xvjf $1     ;;
-            *.tar.gz)    tar xvzf $1     ;;
-            *.bz2)       bunzip2 $1      ;;
-            *.rar)       unrar x $1      ;;
-            *.gz)        gunzip $1       ;;
-            *.tar)       tar xvf $1      ;;
-            *.tbz2)      tar xvjf $1     ;;
-            *.tgz)       tar xvzf $1     ;;
-            *.zip)       unzip $1        ;;
-            *.Z)         uncompress $1   ;;
-            *.7z)        7z x $1         ;;
-            *)           echo "'$1' cannot be extracted via >extract<" ;;
-        esac
-    else
-        echo "'$1' is not a valid file!"
-    fi
+  if [ -f $1 ] ; then
+      case $1 in
+        *.tar.bz2)   tar xvjf $1     ;;
+        *.tar.gz)    tar xvzf $1     ;;
+        *.bz2)       bunzip2 $1      ;;
+        *.rar)       unrar x $1      ;;
+        *.gz)        gunzip $1       ;;
+        *.tar)       tar xvf $1      ;;
+        *.tbz2)      tar xvjf $1     ;;
+        *.tgz)       tar xvzf $1     ;;
+        *.zip)       unzip $1        ;;
+        *.Z)         uncompress $1   ;;
+        *.7z)        7z x $1         ;;
+        *)           echo "'$1' cannot be extracted via >extract<" ;;
+      esac
+  else
+      echo "'$1' is not a valid file!"
+  fi
 }
 
 tst () {
-    month="$1"
-    find . -newermt "01-$month -1 sec" -and -not -newermt "01-$month +1 month -1 sec" -exec tar -rvf $1.tar {} \;
-    gzip -9 $1.tar || echo "No data from $month found."
+  month="$1"
+  find . -newermt "01-$month -1 sec" -and -not -newermt "01-$month +1 month -1 sec" -exec tar -rvf $1.tar {} \;
+  gzip -9 $1.tar || echo "No data from $month found."
 }
 
 dsort () {
-for y in 2019 2018 2017 2016 2015 2014 2013 2012 2011 2010 2009; do
-  echo "Year $y";
-  for x in Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec; do
-    echo "Setting Month to $x";
-    passalong=$x-$y
-    tst $passalong
+  for y in 2019 2018 2017 2016 2015 2014 2013 2012 2011 2010 2009; do
+    echo "Year $y";
+    for x in Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec; do  
+      echo "Setting Month to $x";
+      passalong=$x-$y
+      tst $passalong
+    done
+    echo "Completed year $y..."
   done
-  echo "Completed year $y..."
-done
 }
 
 repeat () {
-    local i max
-    max=$1; shift;
-    for ((i=1; i <= max ; i++)); do  # --> C-like syntax
-        eval "$@";
-    done
+  local i max
+  max=$1; 
+  shift;
+  for ((i=1; i <= max ; i++)); do
+    eval "$@";
+  done
 }
 
 lsnp () { 
-ls -l $1 | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/) *2^(8-i));if(k)printf("%0o ",k);print}'; 
+  ls -l $1 | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/) *2^(8-i));if(k)printf("%0o ",k);print}'; 
 }
 
 statl () {
-stat -c '%a %n' 
+  stat -c '%a %n' 
 }
 
 stripsp () {
-tr -d '\040\011\012\015'
+  tr -d '\040\011\012\015'
 }
+
 stripbl () {
-tr -d '[blank]'
+  tr -d '[blank]'
 }
+
 rmblank () {
-sed '/^\s*$/d'
+  sed '/^\s*$/d'
 }
+
 rmblankw () {
-sed -i '/^\s*$/d'
+  sed -i '/^\s*$/d'
 }
 
 scrub () {
-sed 's/[:graph:]/∎//g'
+  sed 's/[:graph:]/∎//g'
 }
 
 scrubnumbers () {
-sed 's/[0-9]/∎/g'
+  sed 's/[0-9]/∎/g'
 }
+
 alias scbn="scrubnumbers"
 
 scrubletters () {
-sed 's/[a-Z]/∎/g'
+  sed 's/[a-Z]/∎/g'
 }
+
 alias sblts="scrubletters"
 
 bigreport () {
