Update metaRC

diff --git a/metaRC b/metaRC
--- a/metaRC
+++ b/metaRC
@@ -164,57 +164,57 @@ osenc-decrypt () {
 
 
 ufw-root-ssh-ban () {
-for x in $(grep Failed.password.for.root /var/log/auth.log | awk '{print $11}' | sort -u ); do
-  ufw insert 1 deny from $x to any port 22;
-done
-ufw reload
+  for x in $(grep Failed.password.for.root /var/log/auth.log | awk '{print $11}' | sort -u ); do
+    ufw insert 1 deny from $x to any port 22;
+  done
+  ufw reload
 }
 
 ufw-all-ssh-ban () {
-for x in $(grep Failed.password.for /var/log/auth.log | awk '{print $11}' | sort -u ); do
-  ufw insert 1 deny from $x to any port 22;
-done
-ufw reload
+  for x in $(grep Failed.password.for /var/log/auth.log | awk '{print $11}' | sort -u ); do
+    ufw insert 1 deny from $x to any port 22;
+  done
+  ufw reload
 }
 
 ext-ip () { 
-    lynx --dump $1; 
+  lynx --dump $1; 
 }
 
 netest () {
-    val=$(which ss)
-    if [ -z $val ]; then
-      ss -an | grep -v u_str | grep EST
-    else
-      netstat -tan | grep EST
-    fi
+  val=$(which ss)
+  if [ -z $val ]; then
+    ss -an | grep -v u_str | grep EST
+  else
+    netstat -tan | grep EST
+  fi
 }
 
 extract () {
-    if [ -f $1 ] ; then
-        case $1 in
-            *.tar.bz2)   tar xvjf $1     ;;
-            *.tar.gz)    tar xvzf $1     ;;
-            *.bz2)       bunzip2 $1      ;;
-            *.rar)       unrar x $1      ;;
-            *.gz)        gunzip $1       ;;
-            *.tar)       tar xvf $1      ;;
-            *.tbz2)      tar xvjf $1     ;;
-            *.tgz)       tar xvzf $1     ;;
-            *.zip)       unzip $1        ;;
-            *.Z)         uncompress $1   ;;
-            *.7z)        7z x $1         ;;
-            *)           echo "'$1' cannot be extracted via >extract<" ;;
-        esac
-    else
-        echo "'$1' is not a valid file!"
-    fi
+  if [ -f $1 ] ; then
+      case $1 in
+          *.tar.bz2)   tar xvjf $1     ;;
+          *.tar.gz)    tar xvzf $1     ;;
+          *.bz2)       bunzip2 $1      ;;
+          *.rar)       unrar x $1      ;;
+          *.gz)        gunzip $1       ;;
+          *.tar)       tar xvf $1      ;;
+          *.tbz2)      tar xvjf $1     ;;
+          *.tgz)       tar xvzf $1     ;;
+          *.zip)       unzip $1        ;;
+          *.Z)         uncompress $1   ;;
+          *.7z)        7z x $1         ;;
+          *)           echo "'$1' cannot be extracted via >extract<" ;;
+      esac
+  else
+      echo "'$1' is not a valid file!"
+  fi
 }
 
 tst () {
-    month="$1"
-    find . -newermt "01-$month -1 sec" -and -not -newermt "01-$month +1 month -1 sec" -exec tar -rvf $1.tar {} \;
-    gzip -9 $1.tar || echo "No data from $month found."
+  month="$1"
+  find . -newermt "01-$month -1 sec" -and -not -newermt "01-$month +1 month -1 sec" -exec tar -rvf $1.tar {} \;
+  gzip -9 $1.tar || echo "No data from $month found."
 }
 
 dsort () {
@@ -229,93 +229,85 @@ for y in 2020 2019 2018 2017 2016 2015 2014 2013 2012 2011 2010; do
 done
 }
 
-repeat () {
-    local i max
-    max=$1; shift;
-    for ((i=1; i <= max ; i++)); do  # --> C-like syntax
-        eval "$@";
-    done
-}
-
 lsnp() { 
-ls -l $1 | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/) *2^(8-i));if(k)printf("%0o ",k);print}'; 
+  ls -l $1 | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/) *2^(8-i));if(k)printf("%0o ",k);print}'; 
 }
 
 statl () {
-stat -c '%a %n' 
+  stat -c '%a %n' 
 }
 
 remindperms () {
-echo "0    (No read, no write, no execute)     ---"
-echo "1    (No read, no write, execute)    --x"
-echo "2    (No read, write, no execute)    -w-"
-echo "3    (No read, write, execute)    -wx"
-echo "4    (Read, no write, no execute)    r--"
-echo "5    (Read, no write, execute)    r-x"
-echo "6    (Read, write, no execute)    rw-"
-echo "7    (Read, write, execute)   rwx"
-echo "(who)    u        User"
-echo "(who)    g	    Group owner"
-echo "(who)    o	    Other"
-echo "(who)    a	    All (“world”)"
-echo "(action)     +        Adding permissions"
-echo "(action)     -	    Removing permissions"
-echo "(action)     =	    Explicitly set permissions"
-echo "(permissions)    r	    Read"
-echo "(permissions)    w	    Write"
-echo "(permissions)    x	    Execute"
-echo "(permissions)    t	    Sticky bit"
-echo "(permissions)    s	    Set UID or GID"
+  echo "0    (No read, no write, no execute)     ---"
+  echo "1    (No read, no write, execute)    --x"
+  echo "2    (No read, write, no execute)    -w-"
+  echo "3    (No read, write, execute)    -wx"
+  echo "4    (Read, no write, no execute)    r--"
+  echo "5    (Read, no write, execute)    r-x"
+  echo "6    (Read, write, no execute)    rw-"
+  echo "7    (Read, write, execute)   rwx"
+  echo "(who)    u        User"
+  echo "(who)    g	    Group owner"
+  echo "(who)    o	    Other"
+  echo "(who)    a	    All (“world”)"
+  echo "(action)     +        Adding permissions"
+  echo "(action)     -	    Removing permissions"
+  echo "(action)     =	    Explicitly set permissions"
+  echo "(permissions)    r	    Read"
+  echo "(permissions)    w	    Write"
+  echo "(permissions)    x	    Execute"
+  echo "(permissions)    t	    Sticky bit"
+  echo "(permissions)    s	    Set UID or GID"
 }
 
-colorz() {
+colorz () {
 for fgbg in 38 48 ; do # Foreground / Background
-    for color in {0..255} ; do # Colors
-        # Display the color
-        printf "\e[${fgbg};5;%sm  %3s  \e[0m" $color $color
-        # Display 6 colors per lines
-        if [ $((($color + 1) % 6)) == 4 ] ; then
-            echo # New line
-        fi
-    done
-    echo # New line
+  for color in {0..255} ; do # Colors
+      # Display the color
+      printf "\e[${fgbg};5;%sm  %3s  \e[0m" $color $color
+      # Display 6 colors per lines
+      if [ $((($color + 1) % 6)) == 4 ] ; then
+          echo # New line
+      fi
+  done
+  echo # New line
 done
 }
 
 stripsp () {
-tr -d '\040\011\012\015'
+  tr -d '\040\011\012\015'
 }
 stripbl () {
-tr -d '[blank]'
+  tr -d '[blank]'
 }
 rmblank () {
-sed '/^\s*$/d'
+  sed '/^\s*$/d'
 }
 rmblankw () {
-sed -i '/^\s*$/d'
+  sed -i '/^\s*$/d'
 }
 
 scrub () {
-sed 's/[:graph:]/∎/g'
+  sed 's/[:graph:]/∎/g'
 }
 
 scrubnumberswithlove () {
-sed 's/[0-9]//♥/g'
+  sed 's/[0-9]//♥/g'
 }
 alias snwl="scrubnumberswithlove"
 
 scrubletterswithlove () {
-sed 's/[a-Z]/♥/g'
+  sed 's/[a-Z]/♥/g'
 }
 alias slwl="scrubletterswithlove"
 
 scrubnumbers () {
-sed 's/[0-9]/∎/g'
+  sed 's/[0-9]/∎/g'
 }
 alias scbn="scrubnumbers"
 
 scrubletters () {
-sed 's/[a-Z]/∎/g'
+  sed 's/[a-Z]/∎/g'
 }
 alias sblts="scrubletters"
 
@@ -360,19 +352,19 @@ export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; histor
 # Convert common decimals to binary.
 # The int2bin function can only handle 20 character inputs at a time.
 int2bin () {
-    num="$1"
-    bin=""
-    padding=""
-    base2=(0 1)
-    while [ "$num" -gt 0 ]; do
-        bin=${base2[$(($num % 2))]}$bin
-        num=$(($num / 2))
-    done
-    if [ $((8 - (${#bin} % 8))) -ne 8 ]; then
-        printf -v padding '%*s' $((8 - (${#bin} % 8))) ''
-        padding=${padding// /0}
-    fi
-    echo $padding$bin
+  num="$1"
+  bin=""
+  padding=""
+  base2=(0 1)
+  while [ "$num" -gt 0 ]; do
+      bin=${base2[$(($num % 2))]}$bin
+      num=$(($num / 2))
+  done
+  if [ $((8 - (${#bin} % 8))) -ne 8 ]; then
+      printf -v padding '%*s' $((8 - (${#bin} % 8))) ''
+      padding=${padding// /0}
+  fi
+  echo $padding$bin
 }
 
 # Call tr program to remove whitespace of all kinds
@@ -380,12 +372,12 @@ int2bin () {
 
 # Convert binary to decimal. This thing needs work.
 bin2dec () {
-    echo $((2#$1))
+  echo $((2#$1))
 }
 
 # Return the seed length.
 msglgth () {
-SETMSGLGTH=$(cat ~/seeds/a.xor | wc -c)
+  SETMSGLGTH=$(cat ~/seeds/a.xor | wc -c)
 }
 
 # Bitwise XOR.
@@ -394,17 +386,19 @@ bash ~/Scripts/xor.sh
 }
 # Repeat n times command.
 repeat () {
-    local i max
-    max=$1; shift;
-    for ((i=1; i <= max ; i++)); do  # --> C-like syntax
-        eval "$@";
-    done
+  local i max
+  max=$1; 
+  shift;
+  for ((i=1; i <= max ; i++)); do
+    eval "$@";
+  done
 }
+
 # One-time-pad batch XOR.
 otpbatch () {
 for datasets in $(ls ~/seeds/*); do 
-    cat $datasets | stripper > ~/seeds/b.xor; 
-    exor > "$datasets".output; 
+  cat $datasets | stripper > ~/seeds/b.xor; 
+  exor > "$datasets".output; 
 done 2> /dev/null &
 }
 
@@ -421,28 +415,28 @@ done
 # Run a validation check on the seed files.
 libvalidate () {
 for data in $(ls ~/seeds/*); do
-    echo "$data"; 
-    cat "$data" | wc -c; 
-    echo "$data stripped"; 
-    cat "$data" | stripper | wc -c; 
+  echo "$data"; 
+  cat "$data" | wc -c; 
+  echo "$data stripped"; 
+  cat "$data" | stripper | wc -c; 
 done
 }
 
 # Generate a medium sized library of binary digits for playing with.
 libgen () { 
-    for x in {1000..9999}; 
-        do int2bin "$x" > "$x".xor ; 
-    done
+  for x in {1000..9999}; 
+    do int2bin "$x" > "$x".xor ; 
+  done
 }
 
 ######### Python extra tools section below.
 
 byteconv() {
-python -c "import pprint;pprint.pprint(zip(('Byte', 'KByte', 'MByte', 'GByte', 'TByte'), (1 << 10*i for i in xrange(5))))"
+  python -c "import pprint;pprint.pprint(zip(('Byte', 'KByte', 'MByte', 'GByte', 'TByte'), (1 << 10*i for i in xrange(5))))"
 }
 sv2json() {
-python -c "import csv,json;print json.dumps(list(csv.reader(open('csv_file.csv'))))"
+  python -c "import csv,json;print json.dumps(list(csv.reader(open('csv_file.csv'))))"
 }
 dhex() {
-export HEXIN=$1 ; python -c "print ''.join(chr(int(''.join(i), 16)) for i in zip(*[iter('$HEXIN')]*2))"; 
+  export HEXIN=$1 ; python -c "print ''.join(chr(int(''.join(i), 16)) for i in zip(*[iter('$HEXIN')]*2))"; 
 }
